// Code generated by protoc-gen-go. DO NOT EDIT.
// source: webfont.proto

package webfontsdk

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FontListRequest struct {
	Apikey               string   `protobuf:"bytes,1,opt,name=apikey,proto3" json:"apikey,omitempty" bson:"apikey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *FontListRequest) Reset()         { *m = FontListRequest{} }
func (m *FontListRequest) String() string { return proto.CompactTextString(m) }
func (*FontListRequest) ProtoMessage()    {}
func (*FontListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e04e5ea2200a7886, []int{0}
}

func (m *FontListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FontListRequest.Unmarshal(m, b)
}
func (m *FontListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FontListRequest.Marshal(b, m, deterministic)
}
func (m *FontListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FontListRequest.Merge(m, src)
}
func (m *FontListRequest) XXX_Size() int {
	return xxx_messageInfo_FontListRequest.Size(m)
}
func (m *FontListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FontListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FontListRequest proto.InternalMessageInfo

func (m *FontListRequest) GetApikey() string {
	if m != nil {
		return m.Apikey
	}
	return ""
}

type FontListResult struct {
	Fonts                map[uint32]int64 `protobuf:"bytes,1,rep,name=fonts,proto3" json:"fonts,omitempty" bson:"fonts,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-" bson:"-"`
	XXX_unrecognized     []byte           `json:"-" bson:"-"`
	XXX_sizecache        int32            `json:"-" bson:"-"`
}

func (m *FontListResult) Reset()         { *m = FontListResult{} }
func (m *FontListResult) String() string { return proto.CompactTextString(m) }
func (*FontListResult) ProtoMessage()    {}
func (*FontListResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_e04e5ea2200a7886, []int{1}
}

func (m *FontListResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FontListResult.Unmarshal(m, b)
}
func (m *FontListResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FontListResult.Marshal(b, m, deterministic)
}
func (m *FontListResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FontListResult.Merge(m, src)
}
func (m *FontListResult) XXX_Size() int {
	return xxx_messageInfo_FontListResult.Size(m)
}
func (m *FontListResult) XXX_DiscardUnknown() {
	xxx_messageInfo_FontListResult.DiscardUnknown(m)
}

var xxx_messageInfo_FontListResult proto.InternalMessageInfo

func (m *FontListResult) GetFonts() map[uint32]int64 {
	if m != nil {
		return m.Fonts
	}
	return nil
}

type FontBuildRequest struct {
	Apikey               string   `protobuf:"bytes,1,opt,name=apikey,proto3" json:"apikey,omitempty" bson:"apikey,omitempty"`
	FontId               uint32   `protobuf:"varint,2,opt,name=font_id,json=fontId,proto3" json:"font_id,omitempty" bson:"font_id,omitempty"`
	Text                 string   `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty" bson:"text,omitempty"`
	NeedTtf              bool     `protobuf:"varint,4,opt,name=need_ttf,json=needTtf,proto3" json:"need_ttf,omitempty" bson:"need_ttf,omitempty"`
	NeedEot              bool     `protobuf:"varint,5,opt,name=need_eot,json=needEot,proto3" json:"need_eot,omitempty" bson:"need_eot,omitempty"`
	NeedWoff             bool     `protobuf:"varint,6,opt,name=need_woff,json=needWoff,proto3" json:"need_woff,omitempty" bson:"need_woff,omitempty"`
	NeedWoff2            bool     `protobuf:"varint,7,opt,name=need_woff2,json=needWoff2,proto3" json:"need_woff2,omitempty" bson:"need_woff2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *FontBuildRequest) Reset()         { *m = FontBuildRequest{} }
func (m *FontBuildRequest) String() string { return proto.CompactTextString(m) }
func (*FontBuildRequest) ProtoMessage()    {}
func (*FontBuildRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e04e5ea2200a7886, []int{2}
}

func (m *FontBuildRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FontBuildRequest.Unmarshal(m, b)
}
func (m *FontBuildRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FontBuildRequest.Marshal(b, m, deterministic)
}
func (m *FontBuildRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FontBuildRequest.Merge(m, src)
}
func (m *FontBuildRequest) XXX_Size() int {
	return xxx_messageInfo_FontBuildRequest.Size(m)
}
func (m *FontBuildRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FontBuildRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FontBuildRequest proto.InternalMessageInfo

func (m *FontBuildRequest) GetApikey() string {
	if m != nil {
		return m.Apikey
	}
	return ""
}

func (m *FontBuildRequest) GetFontId() uint32 {
	if m != nil {
		return m.FontId
	}
	return 0
}

func (m *FontBuildRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *FontBuildRequest) GetNeedTtf() bool {
	if m != nil {
		return m.NeedTtf
	}
	return false
}

func (m *FontBuildRequest) GetNeedEot() bool {
	if m != nil {
		return m.NeedEot
	}
	return false
}

func (m *FontBuildRequest) GetNeedWoff() bool {
	if m != nil {
		return m.NeedWoff
	}
	return false
}

func (m *FontBuildRequest) GetNeedWoff2() bool {
	if m != nil {
		return m.NeedWoff2
	}
	return false
}

type MultFontBuildRequest struct {
	Items                []*FontBuildRequest `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty" bson:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-" bson:"-"`
	XXX_unrecognized     []byte              `json:"-" bson:"-"`
	XXX_sizecache        int32               `json:"-" bson:"-"`
}

func (m *MultFontBuildRequest) Reset()         { *m = MultFontBuildRequest{} }
func (m *MultFontBuildRequest) String() string { return proto.CompactTextString(m) }
func (*MultFontBuildRequest) ProtoMessage()    {}
func (*MultFontBuildRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e04e5ea2200a7886, []int{3}
}

func (m *MultFontBuildRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultFontBuildRequest.Unmarshal(m, b)
}
func (m *MultFontBuildRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultFontBuildRequest.Marshal(b, m, deterministic)
}
func (m *MultFontBuildRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultFontBuildRequest.Merge(m, src)
}
func (m *MultFontBuildRequest) XXX_Size() int {
	return xxx_messageInfo_MultFontBuildRequest.Size(m)
}
func (m *MultFontBuildRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MultFontBuildRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MultFontBuildRequest proto.InternalMessageInfo

func (m *MultFontBuildRequest) GetItems() []*FontBuildRequest {
	if m != nil {
		return m.Items
	}
	return nil
}

type FontBuildBufResult struct {
	FontId               uint32   `protobuf:"varint,1,opt,name=font_id,json=fontId,proto3" json:"font_id,omitempty" bson:"font_id,omitempty"`
	FontFormatVersion    uint32   `protobuf:"varint,2,opt,name=font_format_version,json=fontFormatVersion,proto3" json:"font_format_version,omitempty" bson:"font_format_version,omitempty"`
	FontChecksum         uint32   `protobuf:"varint,3,opt,name=font_checksum,json=fontChecksum,proto3" json:"font_checksum,omitempty" bson:"font_checksum,omitempty"`
	NameEn               string   `protobuf:"bytes,4,opt,name=name_en,json=nameEn,proto3" json:"name_en,omitempty" bson:"name_en,omitempty"`
	BytesTtf             []byte   `protobuf:"bytes,5,opt,name=bytes_ttf,json=bytesTtf,proto3" json:"bytes_ttf,omitempty" bson:"bytes_ttf,omitempty"`
	BytesEot             []byte   `protobuf:"bytes,6,opt,name=bytes_eot,json=bytesEot,proto3" json:"bytes_eot,omitempty" bson:"bytes_eot,omitempty"`
	BytesWoff            []byte   `protobuf:"bytes,7,opt,name=bytes_woff,json=bytesWoff,proto3" json:"bytes_woff,omitempty" bson:"bytes_woff,omitempty"`
	BytesWoff2           []byte   `protobuf:"bytes,8,opt,name=bytes_woff2,json=bytesWoff2,proto3" json:"bytes_woff2,omitempty" bson:"bytes_woff2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *FontBuildBufResult) Reset()         { *m = FontBuildBufResult{} }
func (m *FontBuildBufResult) String() string { return proto.CompactTextString(m) }
func (*FontBuildBufResult) ProtoMessage()    {}
func (*FontBuildBufResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_e04e5ea2200a7886, []int{4}
}

func (m *FontBuildBufResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FontBuildBufResult.Unmarshal(m, b)
}
func (m *FontBuildBufResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FontBuildBufResult.Marshal(b, m, deterministic)
}
func (m *FontBuildBufResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FontBuildBufResult.Merge(m, src)
}
func (m *FontBuildBufResult) XXX_Size() int {
	return xxx_messageInfo_FontBuildBufResult.Size(m)
}
func (m *FontBuildBufResult) XXX_DiscardUnknown() {
	xxx_messageInfo_FontBuildBufResult.DiscardUnknown(m)
}

var xxx_messageInfo_FontBuildBufResult proto.InternalMessageInfo

func (m *FontBuildBufResult) GetFontId() uint32 {
	if m != nil {
		return m.FontId
	}
	return 0
}

func (m *FontBuildBufResult) GetFontFormatVersion() uint32 {
	if m != nil {
		return m.FontFormatVersion
	}
	return 0
}

func (m *FontBuildBufResult) GetFontChecksum() uint32 {
	if m != nil {
		return m.FontChecksum
	}
	return 0
}

func (m *FontBuildBufResult) GetNameEn() string {
	if m != nil {
		return m.NameEn
	}
	return ""
}

func (m *FontBuildBufResult) GetBytesTtf() []byte {
	if m != nil {
		return m.BytesTtf
	}
	return nil
}

func (m *FontBuildBufResult) GetBytesEot() []byte {
	if m != nil {
		return m.BytesEot
	}
	return nil
}

func (m *FontBuildBufResult) GetBytesWoff() []byte {
	if m != nil {
		return m.BytesWoff
	}
	return nil
}

func (m *FontBuildBufResult) GetBytesWoff2() []byte {
	if m != nil {
		return m.BytesWoff2
	}
	return nil
}

type MultFontBuildBufResult struct {
	Items                []*FontBuildBufResult `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty" bson:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-" bson:"-"`
	XXX_unrecognized     []byte                `json:"-" bson:"-"`
	XXX_sizecache        int32                 `json:"-" bson:"-"`
}

func (m *MultFontBuildBufResult) Reset()         { *m = MultFontBuildBufResult{} }
func (m *MultFontBuildBufResult) String() string { return proto.CompactTextString(m) }
func (*MultFontBuildBufResult) ProtoMessage()    {}
func (*MultFontBuildBufResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_e04e5ea2200a7886, []int{5}
}

func (m *MultFontBuildBufResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultFontBuildBufResult.Unmarshal(m, b)
}
func (m *MultFontBuildBufResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultFontBuildBufResult.Marshal(b, m, deterministic)
}
func (m *MultFontBuildBufResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultFontBuildBufResult.Merge(m, src)
}
func (m *MultFontBuildBufResult) XXX_Size() int {
	return xxx_messageInfo_MultFontBuildBufResult.Size(m)
}
func (m *MultFontBuildBufResult) XXX_DiscardUnknown() {
	xxx_messageInfo_MultFontBuildBufResult.DiscardUnknown(m)
}

var xxx_messageInfo_MultFontBuildBufResult proto.InternalMessageInfo

func (m *MultFontBuildBufResult) GetItems() []*FontBuildBufResult {
	if m != nil {
		return m.Items
	}
	return nil
}

//GetProfile for html5
type GetProfileWithoutMapRequest struct {
	Apikey               string   `protobuf:"bytes,1,opt,name=apikey,proto3" json:"apikey,omitempty" bson:"apikey,omitempty"`
	FontId               uint32   `protobuf:"varint,2,opt,name=font_id,json=fontId,proto3" json:"font_id,omitempty" bson:"font_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *GetProfileWithoutMapRequest) Reset()         { *m = GetProfileWithoutMapRequest{} }
func (m *GetProfileWithoutMapRequest) String() string { return proto.CompactTextString(m) }
func (*GetProfileWithoutMapRequest) ProtoMessage()    {}
func (*GetProfileWithoutMapRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e04e5ea2200a7886, []int{6}
}

func (m *GetProfileWithoutMapRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProfileWithoutMapRequest.Unmarshal(m, b)
}
func (m *GetProfileWithoutMapRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProfileWithoutMapRequest.Marshal(b, m, deterministic)
}
func (m *GetProfileWithoutMapRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProfileWithoutMapRequest.Merge(m, src)
}
func (m *GetProfileWithoutMapRequest) XXX_Size() int {
	return xxx_messageInfo_GetProfileWithoutMapRequest.Size(m)
}
func (m *GetProfileWithoutMapRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProfileWithoutMapRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProfileWithoutMapRequest proto.InternalMessageInfo

func (m *GetProfileWithoutMapRequest) GetApikey() string {
	if m != nil {
		return m.Apikey
	}
	return ""
}

func (m *GetProfileWithoutMapRequest) GetFontId() uint32 {
	if m != nil {
		return m.FontId
	}
	return 0
}

type GetProfileWithoutMapResult struct {
	FontId               uint32   `protobuf:"varint,1,opt,name=font_id,json=fontId,proto3" json:"font_id,omitempty" bson:"font_id,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty" bson:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *GetProfileWithoutMapResult) Reset()         { *m = GetProfileWithoutMapResult{} }
func (m *GetProfileWithoutMapResult) String() string { return proto.CompactTextString(m) }
func (*GetProfileWithoutMapResult) ProtoMessage()    {}
func (*GetProfileWithoutMapResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_e04e5ea2200a7886, []int{7}
}

func (m *GetProfileWithoutMapResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProfileWithoutMapResult.Unmarshal(m, b)
}
func (m *GetProfileWithoutMapResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProfileWithoutMapResult.Marshal(b, m, deterministic)
}
func (m *GetProfileWithoutMapResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProfileWithoutMapResult.Merge(m, src)
}
func (m *GetProfileWithoutMapResult) XXX_Size() int {
	return xxx_messageInfo_GetProfileWithoutMapResult.Size(m)
}
func (m *GetProfileWithoutMapResult) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProfileWithoutMapResult.DiscardUnknown(m)
}

var xxx_messageInfo_GetProfileWithoutMapResult proto.InternalMessageInfo

func (m *GetProfileWithoutMapResult) GetFontId() uint32 {
	if m != nil {
		return m.FontId
	}
	return 0
}

func (m *GetProfileWithoutMapResult) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetMultGlyfsUnicodeRequest struct {
	Apikey               string   `protobuf:"bytes,1,opt,name=apikey,proto3" json:"apikey,omitempty" bson:"apikey,omitempty"`
	FontId               uint32   `protobuf:"varint,2,opt,name=font_id,json=fontId,proto3" json:"font_id,omitempty" bson:"font_id,omitempty"`
	FontChecksum         uint32   `protobuf:"varint,3,opt,name=font_checksum,json=fontChecksum,proto3" json:"font_checksum,omitempty" bson:"font_checksum,omitempty"`
	Unicodes             []uint32 `protobuf:"varint,4,rep,packed,name=unicodes,proto3" json:"unicodes,omitempty" bson:"unicodes,omitempty"`
	AppendZero           bool     `protobuf:"varint,5,opt,name=append_zero,json=appendZero,proto3" json:"append_zero,omitempty" bson:"append_zero,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *GetMultGlyfsUnicodeRequest) Reset()         { *m = GetMultGlyfsUnicodeRequest{} }
func (m *GetMultGlyfsUnicodeRequest) String() string { return proto.CompactTextString(m) }
func (*GetMultGlyfsUnicodeRequest) ProtoMessage()    {}
func (*GetMultGlyfsUnicodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e04e5ea2200a7886, []int{8}
}

func (m *GetMultGlyfsUnicodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMultGlyfsUnicodeRequest.Unmarshal(m, b)
}
func (m *GetMultGlyfsUnicodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMultGlyfsUnicodeRequest.Marshal(b, m, deterministic)
}
func (m *GetMultGlyfsUnicodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMultGlyfsUnicodeRequest.Merge(m, src)
}
func (m *GetMultGlyfsUnicodeRequest) XXX_Size() int {
	return xxx_messageInfo_GetMultGlyfsUnicodeRequest.Size(m)
}
func (m *GetMultGlyfsUnicodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMultGlyfsUnicodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMultGlyfsUnicodeRequest proto.InternalMessageInfo

func (m *GetMultGlyfsUnicodeRequest) GetApikey() string {
	if m != nil {
		return m.Apikey
	}
	return ""
}

func (m *GetMultGlyfsUnicodeRequest) GetFontId() uint32 {
	if m != nil {
		return m.FontId
	}
	return 0
}

func (m *GetMultGlyfsUnicodeRequest) GetFontChecksum() uint32 {
	if m != nil {
		return m.FontChecksum
	}
	return 0
}

func (m *GetMultGlyfsUnicodeRequest) GetUnicodes() []uint32 {
	if m != nil {
		return m.Unicodes
	}
	return nil
}

func (m *GetMultGlyfsUnicodeRequest) GetAppendZero() bool {
	if m != nil {
		return m.AppendZero
	}
	return false
}

type Indexs struct {
	Items                []uint32 `protobuf:"varint,2,rep,packed,name=items,proto3" json:"items,omitempty" bson:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *Indexs) Reset()         { *m = Indexs{} }
func (m *Indexs) String() string { return proto.CompactTextString(m) }
func (*Indexs) ProtoMessage()    {}
func (*Indexs) Descriptor() ([]byte, []int) {
	return fileDescriptor_e04e5ea2200a7886, []int{9}
}

func (m *Indexs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Indexs.Unmarshal(m, b)
}
func (m *Indexs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Indexs.Marshal(b, m, deterministic)
}
func (m *Indexs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Indexs.Merge(m, src)
}
func (m *Indexs) XXX_Size() int {
	return xxx_messageInfo_Indexs.Size(m)
}
func (m *Indexs) XXX_DiscardUnknown() {
	xxx_messageInfo_Indexs.DiscardUnknown(m)
}

var xxx_messageInfo_Indexs proto.InternalMessageInfo

func (m *Indexs) GetItems() []uint32 {
	if m != nil {
		return m.Items
	}
	return nil
}

type GetMultGlyfsUnicodeResult struct {
	Unicodes             map[uint32]*Indexs `protobuf:"bytes,1,rep,name=unicodes,proto3" json:"unicodes,omitempty" bson:"unicodes,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Indexs               map[uint32][]byte  `protobuf:"bytes,3,rep,name=indexs,proto3" json:"indexs,omitempty" bson:"indexs,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-" bson:"-"`
	XXX_unrecognized     []byte             `json:"-" bson:"-"`
	XXX_sizecache        int32              `json:"-" bson:"-"`
}

func (m *GetMultGlyfsUnicodeResult) Reset()         { *m = GetMultGlyfsUnicodeResult{} }
func (m *GetMultGlyfsUnicodeResult) String() string { return proto.CompactTextString(m) }
func (*GetMultGlyfsUnicodeResult) ProtoMessage()    {}
func (*GetMultGlyfsUnicodeResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_e04e5ea2200a7886, []int{10}
}

func (m *GetMultGlyfsUnicodeResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMultGlyfsUnicodeResult.Unmarshal(m, b)
}
func (m *GetMultGlyfsUnicodeResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMultGlyfsUnicodeResult.Marshal(b, m, deterministic)
}
func (m *GetMultGlyfsUnicodeResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMultGlyfsUnicodeResult.Merge(m, src)
}
func (m *GetMultGlyfsUnicodeResult) XXX_Size() int {
	return xxx_messageInfo_GetMultGlyfsUnicodeResult.Size(m)
}
func (m *GetMultGlyfsUnicodeResult) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMultGlyfsUnicodeResult.DiscardUnknown(m)
}

var xxx_messageInfo_GetMultGlyfsUnicodeResult proto.InternalMessageInfo

func (m *GetMultGlyfsUnicodeResult) GetUnicodes() map[uint32]*Indexs {
	if m != nil {
		return m.Unicodes
	}
	return nil
}

func (m *GetMultGlyfsUnicodeResult) GetIndexs() map[uint32][]byte {
	if m != nil {
		return m.Indexs
	}
	return nil
}

func init() {
	proto.RegisterType((*FontListRequest)(nil), "webfontsdk.FontListRequest")
	proto.RegisterType((*FontListResult)(nil), "webfontsdk.FontListResult")
	proto.RegisterMapType((map[uint32]int64)(nil), "webfontsdk.FontListResult.FontsEntry")
	proto.RegisterType((*FontBuildRequest)(nil), "webfontsdk.FontBuildRequest")
	proto.RegisterType((*MultFontBuildRequest)(nil), "webfontsdk.MultFontBuildRequest")
	proto.RegisterType((*FontBuildBufResult)(nil), "webfontsdk.FontBuildBufResult")
	proto.RegisterType((*MultFontBuildBufResult)(nil), "webfontsdk.MultFontBuildBufResult")
	proto.RegisterType((*GetProfileWithoutMapRequest)(nil), "webfontsdk.GetProfileWithoutMapRequest")
	proto.RegisterType((*GetProfileWithoutMapResult)(nil), "webfontsdk.GetProfileWithoutMapResult")
	proto.RegisterType((*GetMultGlyfsUnicodeRequest)(nil), "webfontsdk.GetMultGlyfsUnicodeRequest")
	proto.RegisterType((*Indexs)(nil), "webfontsdk.indexs")
	proto.RegisterType((*GetMultGlyfsUnicodeResult)(nil), "webfontsdk.GetMultGlyfsUnicodeResult")
	proto.RegisterMapType((map[uint32][]byte)(nil), "webfontsdk.GetMultGlyfsUnicodeResult.IndexsEntry")
	proto.RegisterMapType((map[uint32]*Indexs)(nil), "webfontsdk.GetMultGlyfsUnicodeResult.UnicodesEntry")
}

func init() { proto.RegisterFile("webfont.proto", fileDescriptor_e04e5ea2200a7886) }

var fileDescriptor_e04e5ea2200a7886 = []byte{
	// 759 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0xdd, 0x4e, 0xdb, 0x4a,
	0x10, 0xc6, 0xf9, 0xcf, 0x24, 0x3e, 0x87, 0xb3, 0x20, 0x8e, 0x31, 0x07, 0x4e, 0xe4, 0x0a, 0x9a,
	0xde, 0x44, 0xaa, 0xe9, 0x05, 0x6d, 0xef, 0x52, 0x05, 0x94, 0xb6, 0xfc, 0xc8, 0x6a, 0x1b, 0xa9,
	0x37, 0x91, 0x89, 0xd7, 0xc5, 0x22, 0xf1, 0xa6, 0xf6, 0x1a, 0x48, 0x5f, 0xa0, 0x4f, 0xd0, 0xe7,
	0xe8, 0x43, 0xf4, 0x8a, 0xb7, 0xaa, 0x76, 0xd6, 0x89, 0x1d, 0xea, 0x10, 0xc4, 0xdd, 0xce, 0x7e,
	0xdf, 0x7c, 0x63, 0x7f, 0xb3, 0x3b, 0x0b, 0xea, 0x35, 0x3d, 0x77, 0x99, 0xcf, 0x5b, 0xe3, 0x80,
	0x71, 0x46, 0x20, 0x0e, 0x43, 0xe7, 0xd2, 0x78, 0x06, 0x7f, 0x1f, 0x32, 0x9f, 0xbf, 0xf7, 0x42,
	0x6e, 0xd1, 0xaf, 0x11, 0x0d, 0x39, 0xd9, 0x80, 0x92, 0x3d, 0xf6, 0x2e, 0xe9, 0x44, 0x53, 0x1a,
	0x4a, 0xb3, 0x6a, 0xc5, 0x91, 0xf1, 0x5d, 0x81, 0xbf, 0x12, 0x6e, 0x18, 0x0d, 0x39, 0x79, 0x0d,
	0x45, 0x14, 0xd2, 0x94, 0x46, 0xbe, 0x59, 0x33, 0x77, 0x5b, 0x89, 0x72, 0x6b, 0x9e, 0x8a, 0x61,
	0xd8, 0xf1, 0x79, 0x30, 0xb1, 0x64, 0x8e, 0x7e, 0x00, 0x90, 0x6c, 0x92, 0x55, 0xc8, 0x4f, 0x4b,
	0xaa, 0x96, 0x58, 0x92, 0x75, 0x28, 0x5e, 0xd9, 0xc3, 0x88, 0x6a, 0xb9, 0x86, 0xd2, 0xcc, 0x5b,
	0x32, 0x78, 0x95, 0x3b, 0x50, 0x8c, 0x5b, 0x05, 0x56, 0x45, 0x6a, 0x3b, 0xf2, 0x86, 0xce, 0x92,
	0xcf, 0x26, 0xff, 0x42, 0x59, 0xd4, 0xeb, 0x7b, 0x0e, 0x0a, 0xa9, 0x56, 0x49, 0x84, 0x5d, 0x87,
	0x10, 0x28, 0x70, 0x7a, 0xc3, 0xb5, 0x3c, 0xd2, 0x71, 0x4d, 0x36, 0xa1, 0xe2, 0x53, 0xea, 0xf4,
	0x39, 0x77, 0xb5, 0x42, 0x43, 0x69, 0x56, 0xac, 0xb2, 0x88, 0x3f, 0x70, 0x77, 0x06, 0x51, 0xc6,
	0xb5, 0x62, 0x02, 0x75, 0x18, 0x27, 0x5b, 0x50, 0x45, 0xe8, 0x9a, 0xb9, 0xae, 0x56, 0x42, 0x0c,
	0xb9, 0x3d, 0xe6, 0xba, 0x64, 0x1b, 0x60, 0x06, 0x9a, 0x5a, 0x19, 0xd1, 0xea, 0x14, 0x35, 0x8d,
	0xb7, 0xb0, 0x7e, 0x1c, 0x0d, 0xf9, 0x1f, 0xbf, 0x63, 0x42, 0xd1, 0xe3, 0x74, 0x34, 0xb5, 0xf6,
	0xbf, 0xbb, 0xd6, 0xa6, 0xc9, 0x96, 0xa4, 0x1a, 0x3f, 0x72, 0x40, 0x66, 0x58, 0x3b, 0x72, 0xe3,
	0x2e, 0xa5, 0x1c, 0x50, 0xe6, 0x1c, 0x68, 0xc1, 0x1a, 0x02, 0x2e, 0x0b, 0x46, 0x36, 0xef, 0x5f,
	0xd1, 0x20, 0xf4, 0x98, 0x1f, 0xdb, 0xf4, 0x8f, 0x80, 0x0e, 0x11, 0xf9, 0x24, 0x01, 0xf2, 0x04,
	0x54, 0xe4, 0x0f, 0x2e, 0xe8, 0xe0, 0x32, 0x8c, 0x46, 0x68, 0x9d, 0x6a, 0xd5, 0xc5, 0xe6, 0x9b,
	0x78, 0x4f, 0x54, 0xf3, 0xed, 0x11, 0xed, 0x53, 0x1f, 0x1d, 0xac, 0x5a, 0x25, 0x11, 0x76, 0x7c,
	0xe1, 0xd2, 0xf9, 0x84, 0xd3, 0x10, 0xcd, 0x15, 0x0e, 0xd6, 0xad, 0x0a, 0x6e, 0x08, 0x77, 0x67,
	0xa0, 0xb0, 0xb7, 0x94, 0x02, 0x85, 0xbf, 0xdb, 0x00, 0x12, 0x44, 0x83, 0xcb, 0x88, 0x4a, 0x3a,
	0x3a, 0xfc, 0x3f, 0xd4, 0x12, 0xd8, 0xd4, 0x2a, 0x88, 0xc3, 0x0c, 0x37, 0x8d, 0x13, 0xd8, 0x98,
	0xf3, 0x38, 0xb1, 0xe6, 0xc5, 0xbc, 0xcb, 0x3b, 0x99, 0x2e, 0xcf, 0xe8, 0x53, 0x9f, 0x4f, 0x60,
	0xeb, 0x88, 0xf2, 0xb3, 0x80, 0xb9, 0xde, 0x90, 0xf6, 0x3c, 0x7e, 0xc1, 0x22, 0x7e, 0x6c, 0x8f,
	0x1f, 0x7b, 0x12, 0x8d, 0x2e, 0xe8, 0xd9, 0x7a, 0xf7, 0xb7, 0x8f, 0x40, 0xc1, 0xb1, 0xb9, 0x8d,
	0x62, 0x75, 0x0b, 0xd7, 0xc6, 0x4f, 0x05, 0xb5, 0xc4, 0xef, 0x1e, 0x0d, 0x27, 0x6e, 0xf8, 0xd1,
	0xf7, 0x06, 0xcc, 0xa1, 0x8f, 0xbe, 0x24, 0x0f, 0x6a, 0xb9, 0x0e, 0x95, 0x48, 0xd6, 0x09, 0xb5,
	0x42, 0x23, 0xdf, 0x54, 0xad, 0x59, 0x2c, 0x9a, 0x63, 0x8f, 0xc7, 0xd4, 0x77, 0xfa, 0xdf, 0x68,
	0xc0, 0xe2, 0x9b, 0x03, 0x72, 0xeb, 0x33, 0x0d, 0x98, 0xb1, 0x03, 0x25, 0xcf, 0x77, 0xe8, 0x4d,
	0x28, 0x2e, 0xbc, 0x6c, 0x46, 0x0e, 0x35, 0x62, 0xb3, 0x7f, 0xe5, 0x60, 0x33, 0xf3, 0x8f, 0xd0,
	0x9c, 0xd3, 0x54, 0x69, 0xd9, 0xc3, 0xfd, 0x74, 0x0f, 0x17, 0x26, 0xb6, 0xe2, 0x28, 0x1e, 0x49,
	0xc9, 0xf7, 0x76, 0xa7, 0x9f, 0xa3, 0xe5, 0x51, 0xee, 0xf9, 0xc3, 0xe4, 0xba, 0x98, 0x23, 0xc5,
	0x62, 0x01, 0xfd, 0x14, 0xd4, 0xb9, 0x2a, 0x19, 0x33, 0xae, 0x99, 0x9e, 0x71, 0x35, 0x93, 0xa4,
	0x8b, 0x49, 0x95, 0xd4, 0xdc, 0xd3, 0x5f, 0x42, 0x2d, 0x55, 0x67, 0xd9, 0xc8, 0xac, 0xa7, 0x52,
	0xcd, 0xdb, 0x3c, 0x94, 0x8f, 0x02, 0x4a, 0x39, 0x0d, 0xc8, 0x3b, 0xa8, 0xe2, 0xb9, 0x16, 0x07,
	0x9c, 0xdc, 0x3b, 0x58, 0xf4, 0x25, 0x17, 0xc2, 0x58, 0x21, 0x3d, 0x50, 0x85, 0x25, 0x89, 0x60,
	0x23, 0x9d, 0x92, 0x35, 0xda, 0x74, 0x63, 0x21, 0x23, 0x2d, 0xdc, 0x81, 0xca, 0xf4, 0x09, 0x21,
	0x5b, 0xd9, 0x0f, 0x8b, 0x94, 0xd3, 0x17, 0xbf, 0x3a, 0xc6, 0x0a, 0xf1, 0x60, 0x3d, 0xeb, 0x6e,
	0x91, 0xa7, 0x77, 0xfa, 0xba, 0xe8, 0x36, 0xeb, 0x7b, 0xcb, 0x89, 0x71, 0x29, 0x17, 0xd6, 0x32,
	0x0e, 0x08, 0xd9, 0x5b, 0x7a, 0x82, 0x64, 0xa1, 0xdd, 0x07, 0x9d, 0x34, 0x63, 0xa5, 0xbd, 0x0b,
	0x6b, 0x1e, 0x6b, 0x7d, 0x09, 0xc6, 0x83, 0x96, 0xa0, 0xc6, 0x59, 0xed, 0x7a, 0x4f, 0x2e, 0xce,
	0xc4, 0x23, 0x7f, 0xa6, 0x9c, 0x97, 0xf0, 0xb5, 0xdf, 0xff, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x54,
	0x17, 0xca, 0x7f, 0xfe, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreeterClient interface {
	//BuildFont
	BuildFont(ctx context.Context, in *FontBuildRequest, opts ...grpc.CallOption) (*FontBuildBufResult, error)
	//MultBuildFont
	MultBuildFont(ctx context.Context, in *MultFontBuildRequest, opts ...grpc.CallOption) (*MultFontBuildBufResult, error)
	//Get my fontlist
	FontList(ctx context.Context, in *FontListRequest, opts ...grpc.CallOption) (*FontListResult, error)
	//GetProfile
	GetProfileWithoutMap(ctx context.Context, in *GetProfileWithoutMapRequest, opts ...grpc.CallOption) (*GetProfileWithoutMapResult, error)
	//GetMultGlyfsUnicode
	GetMultGlyfsUnicode(ctx context.Context, in *GetMultGlyfsUnicodeRequest, opts ...grpc.CallOption) (*GetMultGlyfsUnicodeResult, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) BuildFont(ctx context.Context, in *FontBuildRequest, opts ...grpc.CallOption) (*FontBuildBufResult, error) {
	out := new(FontBuildBufResult)
	err := c.cc.Invoke(ctx, "/webfontsdk.Greeter/BuildFont", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) MultBuildFont(ctx context.Context, in *MultFontBuildRequest, opts ...grpc.CallOption) (*MultFontBuildBufResult, error) {
	out := new(MultFontBuildBufResult)
	err := c.cc.Invoke(ctx, "/webfontsdk.Greeter/MultBuildFont", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) FontList(ctx context.Context, in *FontListRequest, opts ...grpc.CallOption) (*FontListResult, error) {
	out := new(FontListResult)
	err := c.cc.Invoke(ctx, "/webfontsdk.Greeter/FontList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) GetProfileWithoutMap(ctx context.Context, in *GetProfileWithoutMapRequest, opts ...grpc.CallOption) (*GetProfileWithoutMapResult, error) {
	out := new(GetProfileWithoutMapResult)
	err := c.cc.Invoke(ctx, "/webfontsdk.Greeter/GetProfileWithoutMap", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) GetMultGlyfsUnicode(ctx context.Context, in *GetMultGlyfsUnicodeRequest, opts ...grpc.CallOption) (*GetMultGlyfsUnicodeResult, error) {
	out := new(GetMultGlyfsUnicodeResult)
	err := c.cc.Invoke(ctx, "/webfontsdk.Greeter/GetMultGlyfsUnicode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeterServer is the server API for Greeter service.
type GreeterServer interface {
	//BuildFont
	BuildFont(context.Context, *FontBuildRequest) (*FontBuildBufResult, error)
	//MultBuildFont
	MultBuildFont(context.Context, *MultFontBuildRequest) (*MultFontBuildBufResult, error)
	//Get my fontlist
	FontList(context.Context, *FontListRequest) (*FontListResult, error)
	//GetProfile
	GetProfileWithoutMap(context.Context, *GetProfileWithoutMapRequest) (*GetProfileWithoutMapResult, error)
	//GetMultGlyfsUnicode
	GetMultGlyfsUnicode(context.Context, *GetMultGlyfsUnicodeRequest) (*GetMultGlyfsUnicodeResult, error)
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_BuildFont_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FontBuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).BuildFont(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/webfontsdk.Greeter/BuildFont",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).BuildFont(ctx, req.(*FontBuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_MultBuildFont_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MultFontBuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).MultBuildFont(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/webfontsdk.Greeter/MultBuildFont",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).MultBuildFont(ctx, req.(*MultFontBuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_FontList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FontListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).FontList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/webfontsdk.Greeter/FontList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).FontList(ctx, req.(*FontListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_GetProfileWithoutMap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProfileWithoutMapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).GetProfileWithoutMap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/webfontsdk.Greeter/GetProfileWithoutMap",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).GetProfileWithoutMap(ctx, req.(*GetProfileWithoutMapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_GetMultGlyfsUnicode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMultGlyfsUnicodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).GetMultGlyfsUnicode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/webfontsdk.Greeter/GetMultGlyfsUnicode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).GetMultGlyfsUnicode(ctx, req.(*GetMultGlyfsUnicodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "webfontsdk.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BuildFont",
			Handler:    _Greeter_BuildFont_Handler,
		},
		{
			MethodName: "MultBuildFont",
			Handler:    _Greeter_MultBuildFont_Handler,
		},
		{
			MethodName: "FontList",
			Handler:    _Greeter_FontList_Handler,
		},
		{
			MethodName: "GetProfileWithoutMap",
			Handler:    _Greeter_GetProfileWithoutMap_Handler,
		},
		{
			MethodName: "GetMultGlyfsUnicode",
			Handler:    _Greeter_GetMultGlyfsUnicode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "webfont.proto",
}
