# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: webfont.proto for package 'webfontsdk'

require 'grpc'
require 'webfont_pb'

module Webfontsdk
  module Greeter
    # The greeting service definition.
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'webfontsdk.Greeter'

      # BuildFont
      rpc :BuildFont, FontBuildRequest, FontBuildBufResult
      # MultBuildFont
      rpc :MultBuildFont, MultFontBuildRequest, MultFontBuildBufResult
      # Get my fontlist
      rpc :FontList, FontListRequest, FontListResult
    end

    Stub = Service.rpc_stub_class
  end
end
