# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: webfont.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "webfontsdk.FontListRequest" do
    optional :apikey, :string, 1
  end
  add_message "webfontsdk.FontListResult" do
    map :fonts, :uint32, :int64, 1
  end
  add_message "webfontsdk.FontBuildRequest" do
    optional :apikey, :string, 1
    optional :font_id, :uint32, 2
    optional :text, :string, 3
    optional :need_ttf, :bool, 4
    optional :need_eot, :bool, 5
    optional :need_woff, :bool, 6
    optional :need_woff2, :bool, 7
  end
  add_message "webfontsdk.MultFontBuildRequest" do
    repeated :items, :message, 1, "webfontsdk.FontBuildRequest"
  end
  add_message "webfontsdk.FontBuildBufResult" do
    optional :font_id, :uint32, 1
    optional :font_format_version, :uint32, 2
    optional :font_checksum, :uint32, 3
    optional :name_en, :string, 4
    optional :bytes_ttf, :bytes, 5
    optional :bytes_eot, :bytes, 6
    optional :bytes_woff, :bytes, 7
    optional :bytes_woff2, :bytes, 8
  end
  add_message "webfontsdk.MultFontBuildBufResult" do
    repeated :items, :message, 1, "webfontsdk.FontBuildBufResult"
  end
  add_message "webfontsdk.GetProfileWithoutMapRequest" do
    optional :apikey, :string, 1
    optional :font_id, :uint32, 2
  end
  add_message "webfontsdk.GetProfileWithoutMapResult" do
    optional :font_id, :uint32, 1
    optional :data, :bytes, 2
  end
  add_message "webfontsdk.GetMultGlyfsUnicodeRequest" do
    optional :apikey, :string, 1
    optional :font_id, :uint32, 2
    optional :font_checksum, :uint32, 3
    repeated :unicodes, :uint32, 4
    optional :append_zero, :bool, 5
  end
  add_message "webfontsdk.indexs" do
    repeated :items, :uint32, 2
  end
  add_message "webfontsdk.GetMultGlyfsUnicodeResult" do
    map :unicodes, :uint32, :message, 1, "webfontsdk.indexs"
    map :indexs, :uint32, :bytes, 3
  end
end

module Webfontsdk
  FontListRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("webfontsdk.FontListRequest").msgclass
  FontListResult = Google::Protobuf::DescriptorPool.generated_pool.lookup("webfontsdk.FontListResult").msgclass
  FontBuildRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("webfontsdk.FontBuildRequest").msgclass
  MultFontBuildRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("webfontsdk.MultFontBuildRequest").msgclass
  FontBuildBufResult = Google::Protobuf::DescriptorPool.generated_pool.lookup("webfontsdk.FontBuildBufResult").msgclass
  MultFontBuildBufResult = Google::Protobuf::DescriptorPool.generated_pool.lookup("webfontsdk.MultFontBuildBufResult").msgclass
  GetProfileWithoutMapRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("webfontsdk.GetProfileWithoutMapRequest").msgclass
  GetProfileWithoutMapResult = Google::Protobuf::DescriptorPool.generated_pool.lookup("webfontsdk.GetProfileWithoutMapResult").msgclass
  GetMultGlyfsUnicodeRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("webfontsdk.GetMultGlyfsUnicodeRequest").msgclass
  Indexs = Google::Protobuf::DescriptorPool.generated_pool.lookup("webfontsdk.indexs").msgclass
  GetMultGlyfsUnicodeResult = Google::Protobuf::DescriptorPool.generated_pool.lookup("webfontsdk.GetMultGlyfsUnicodeResult").msgclass
end
