// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: webfontproto/webfont.proto

package io.webfont.proto;

public interface FontListResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:webfontsdk.FontListResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *uint32 font_id = 1;
   *uint64 express = 2;
   * </pre>
   *
   * <code>map&lt;uint32, int64&gt; fonts = 1;</code>
   */
  int getFontsCount();
  /**
   * <pre>
   *uint32 font_id = 1;
   *uint64 express = 2;
   * </pre>
   *
   * <code>map&lt;uint32, int64&gt; fonts = 1;</code>
   */
  boolean containsFonts(
      int key);
  /**
   * Use {@link #getFontsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.Integer, java.lang.Long>
  getFonts();
  /**
   * <pre>
   *uint32 font_id = 1;
   *uint64 express = 2;
   * </pre>
   *
   * <code>map&lt;uint32, int64&gt; fonts = 1;</code>
   */
  java.util.Map<java.lang.Integer, java.lang.Long>
  getFontsMap();
  /**
   * <pre>
   *uint32 font_id = 1;
   *uint64 express = 2;
   * </pre>
   *
   * <code>map&lt;uint32, int64&gt; fonts = 1;</code>
   */

  long getFontsOrDefault(
      int key,
      long defaultValue);
  /**
   * <pre>
   *uint32 font_id = 1;
   *uint64 express = 2;
   * </pre>
   *
   * <code>map&lt;uint32, int64&gt; fonts = 1;</code>
   */

  long getFontsOrThrow(
      int key);
}
