// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: webfontproto/webfont.proto

package io.webfont.proto;

public interface FontBuildRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:webfontsdk.FontBuildRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 font_id = 1;</code>
   */
  int getFontId();

  /**
   * <code>string text = 2;</code>
   */
  java.lang.String getText();
  /**
   * <code>string text = 2;</code>
   */
  com.google.protobuf.ByteString
      getTextBytes();

  /**
   * <code>string apikey = 3;</code>
   */
  java.lang.String getApikey();
  /**
   * <code>string apikey = 3;</code>
   */
  com.google.protobuf.ByteString
      getApikeyBytes();

  /**
   * <code>bool need_ttf = 4;</code>
   */
  boolean getNeedTtf();

  /**
   * <code>bool need_eot = 5;</code>
   */
  boolean getNeedEot();

  /**
   * <code>bool need_woff = 6;</code>
   */
  boolean getNeedWoff();
}
