// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: webfontproto/webfont.proto

package io.webfont.proto;

public interface MultFontBuildRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:webfontsdk.MultFontBuildRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .webfontsdk.FontBuildRequest items = 1;</code>
   */
  java.util.List<io.webfont.proto.FontBuildRequest> 
      getItemsList();
  /**
   * <code>repeated .webfontsdk.FontBuildRequest items = 1;</code>
   */
  io.webfont.proto.FontBuildRequest getItems(int index);
  /**
   * <code>repeated .webfontsdk.FontBuildRequest items = 1;</code>
   */
  int getItemsCount();
  /**
   * <code>repeated .webfontsdk.FontBuildRequest items = 1;</code>
   */
  java.util.List<? extends io.webfont.proto.FontBuildRequestOrBuilder> 
      getItemsOrBuilderList();
  /**
   * <code>repeated .webfontsdk.FontBuildRequest items = 1;</code>
   */
  io.webfont.proto.FontBuildRequestOrBuilder getItemsOrBuilder(
      int index);
}
