// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: webfontproto/webfont.proto

package io.webfont.proto;

public interface MultFontBuildBufResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:webfontsdk.MultFontBuildBufResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .webfontsdk.FontBuildBufResult items = 1;</code>
   */
  java.util.List<io.webfont.proto.FontBuildBufResult> 
      getItemsList();
  /**
   * <code>repeated .webfontsdk.FontBuildBufResult items = 1;</code>
   */
  io.webfont.proto.FontBuildBufResult getItems(int index);
  /**
   * <code>repeated .webfontsdk.FontBuildBufResult items = 1;</code>
   */
  int getItemsCount();
  /**
   * <code>repeated .webfontsdk.FontBuildBufResult items = 1;</code>
   */
  java.util.List<? extends io.webfont.proto.FontBuildBufResultOrBuilder> 
      getItemsOrBuilderList();
  /**
   * <code>repeated .webfontsdk.FontBuildBufResult items = 1;</code>
   */
  io.webfont.proto.FontBuildBufResultOrBuilder getItemsOrBuilder(
      int index);
}
